// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiPlanerAPI.Data;

#nullable disable

namespace MultiPlanerAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825144737_InitialSqlServerCreate")]
    partial class InitialSqlServerCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultiPlanerAPI.Models.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("image_link");

                    b.Property<string>("MagicLink")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("magic_link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_calendar");

                    b.ToTable("calendar", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.CalendarCalendarList", b =>
                {
                    b.Property<int>("CalendarId")
                        .HasColumnType("int")
                        .HasColumnName("calendar_id");

                    b.Property<int>("CalendarListId")
                        .HasColumnType("int")
                        .HasColumnName("calendar_list_id");

                    b.HasKey("CalendarId", "CalendarListId")
                        .HasName("pk_calendar_calendar_list");

                    b.HasIndex("CalendarListId");

                    b.ToTable("calendar_calendar_list", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.CalendarEvent", b =>
                {
                    b.Property<int>("CalendarId")
                        .HasColumnType("int")
                        .HasColumnName("calendar_id");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.HasKey("CalendarId", "EventId")
                        .HasName("pk_calendar_event");

                    b.HasIndex("EventId")
                        .IsUnique()
                        .HasDatabaseName("uk_event");

                    b.ToTable("calendar_event", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.CalendarList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalendarSublistId")
                        .HasColumnType("int")
                        .HasColumnName("calendar_sublist_id");

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_calendar_list");

                    b.HasIndex("CalendarSublistId");

                    b.HasIndex("MenuId");

                    b.HasIndex("UserId");

                    b.ToTable("calendar_list", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.CalendarPoll", b =>
                {
                    b.Property<int>("IdCalendar")
                        .HasColumnType("int")
                        .HasColumnName("id_calendar");

                    b.Property<int>("IdPoll")
                        .HasColumnType("int")
                        .HasColumnName("id_poll");

                    b.HasKey("IdCalendar", "IdPoll")
                        .HasName("pk_calendar_poll");

                    b.HasIndex("IdPoll");

                    b.ToTable("calendar_poll", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.CalendarState", b =>
                {
                    b.Property<int>("CalendarId")
                        .HasColumnType("int")
                        .HasColumnName("calendar_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("StateContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("state_content");

                    b.HasKey("CalendarId", "UserId")
                        .HasName("pk_calendar_state");

                    b.HasIndex("UserId");

                    b.ToTable("calendar_state", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.CalendarUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("CalendarId")
                        .HasColumnType("int")
                        .HasColumnName("calendar_id");

                    b.Property<bool>("IsFavourite")
                        .HasColumnType("bit")
                        .HasColumnName("is_favourite");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("joined_at");

                    b.Property<string>("UserAlias")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("user_alias");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("user_role");

                    b.HasKey("UserId", "CalendarId")
                        .HasName("pk_calendar_user");

                    b.HasIndex("CalendarId");

                    b.ToTable("calendar_user", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsHighPriority")
                        .HasColumnType("bit")
                        .HasColumnName("is_high_priority");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_Tbl");

                    b.HasIndex("UserId");

                    b.ToTable("event", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.EventData", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("Color")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndingDate")
                        .HasColumnType("date")
                        .HasColumnName("ending_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartingDate")
                        .HasColumnType("date")
                        .HasColumnName("starting_date");

                    b.HasKey("EventId")
                        .HasName("pk_event_data");

                    b.ToTable("event_data", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.EventUser", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("event_id");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("user_role");

                    b.HasKey("UserId", "EventId")
                        .HasName("pk_event_user");

                    b.HasIndex("EventId");

                    b.ToTable("event_user", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_menu");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("unq_menu");

                    b.ToTable("menu", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.MessageRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarId")
                        .HasColumnType("int")
                        .HasColumnName("calendar_id");

                    b.HasKey("Id")
                        .HasName("pk_message_room");

                    b.HasIndex("CalendarId")
                        .IsUnique()
                        .HasDatabaseName("unq_message_room");

                    b.ToTable("message_room", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.MessageRoomMessages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MessageRoomId")
                        .HasColumnType("int")
                        .HasColumnName("message_room_id");

                    b.Property<string>("Messages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("messages");

                    b.HasKey("Id")
                        .HasName("pk_message_room_messages");

                    b.HasIndex("MessageRoomId")
                        .IsUnique()
                        .HasDatabaseName("unq_message_room_messages");

                    b.ToTable("message_room_messages", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("result");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_poll");

                    b.ToTable("poll", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.PollUser", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    b.Property<int>("IdPoll")
                        .HasColumnType("int")
                        .HasColumnName("id_poll");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("bit")
                        .HasColumnName("is_owner");

                    b.Property<bool>("Voted")
                        .HasColumnType("bit")
                        .HasColumnName("voted");

                    b.HasKey("IdUser", "IdPoll")
                        .HasName("pk_poll_user");

                    b.HasIndex("IdPoll");

                    b.ToTable("poll_user", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAvatar")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("user_avatar");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_ser");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("unq_user");

                    b.ToTable("user", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.UserSettings", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("int")
                        .HasColumnName("id_user");

                    b.HasKey("IdUser")
                        .HasName("pk_user_settings");

                    b.ToTable("user_settings", "dbo");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.CalendarCalendarList", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.Calendar", "Calendar")
                        .WithMany("CalendarCalendarLists")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_calendar_list_calendar");

                    b.HasOne("MultiPlanerAPI.Models.CalendarList", "CalendarList")
                        .WithMany("CalendarCalendarLists")
                        .HasForeignKey("CalendarListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_calendar_list_calendar_list");

                    b.Navigation("Calendar");

                    b.Navigation("CalendarList");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.CalendarEvent", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.Calendar", "Calendar")
                        .WithMany("CalendarEvents")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_event_calendar");

                    b.HasOne("MultiPlanerAPI.Models.Event", "Event")
                        .WithOne("CalendarEvent")
                        .HasForeignKey("MultiPlanerAPI.Models.CalendarEvent", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_event_event");

                    b.Navigation("Calendar");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.CalendarList", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.CalendarList", "CalendarSublist")
                        .WithMany("SubLists")
                        .HasForeignKey("CalendarSublistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_calendar_list_calendar_list");

                    b.HasOne("MultiPlanerAPI.Models.Menu", "Menu")
                        .WithMany("CalendarLists")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_list_menu");

                    b.HasOne("MultiPlanerAPI.Models.User", "User")
                        .WithMany("CalendarLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_calendar_list_user");

                    b.Navigation("CalendarSublist");

                    b.Navigation("Menu");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.CalendarPoll", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.Calendar", "Calendar")
                        .WithMany("CalendarPolls")
                        .HasForeignKey("IdCalendar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_poll_calendar");

                    b.HasOne("MultiPlanerAPI.Models.Poll", "Poll")
                        .WithMany("CalendarPolls")
                        .HasForeignKey("IdPoll")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_poll_poll");

                    b.Navigation("Calendar");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.CalendarState", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.Calendar", "Calendar")
                        .WithMany("CalendarStates")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_state_calendar");

                    b.HasOne("MultiPlanerAPI.Models.User", "User")
                        .WithMany("CalendarStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_state_user");

                    b.Navigation("Calendar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.CalendarUser", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.Calendar", "Calendar")
                        .WithMany("CalendarUsers")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_user_calendar");

                    b.HasOne("MultiPlanerAPI.Models.User", "User")
                        .WithMany("CalendarUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calendar_user_user");

                    b.Navigation("Calendar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.Event", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.User", "User")
                        .WithMany("CreatedEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_event_creator_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.EventData", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.Event", "Event")
                        .WithOne("EventData")
                        .HasForeignKey("MultiPlanerAPI.Models.EventData", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_data_event");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.EventUser", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.Event", "Event")
                        .WithMany("EventUsers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_user_event");

                    b.HasOne("MultiPlanerAPI.Models.User", "User")
                        .WithMany("EventUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_user_user");

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.Menu", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.User", "User")
                        .WithOne("Menu")
                        .HasForeignKey("MultiPlanerAPI.Models.Menu", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_menu_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.MessageRoom", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.Calendar", "Calendar")
                        .WithOne("MessageRoom")
                        .HasForeignKey("MultiPlanerAPI.Models.MessageRoom", "CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_room_calendar");

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.MessageRoomMessages", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.MessageRoom", "MessageRoom")
                        .WithOne("MessageRoomMessages")
                        .HasForeignKey("MultiPlanerAPI.Models.MessageRoomMessages", "MessageRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_room_messages_message_room");

                    b.Navigation("MessageRoom");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.PollUser", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.Poll", "Poll")
                        .WithMany("PollUsers")
                        .HasForeignKey("IdPoll")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poll_user_poll");

                    b.HasOne("MultiPlanerAPI.Models.User", "User")
                        .WithMany("PollUsers")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_poll_user_user");

                    b.Navigation("Poll");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.UserSettings", b =>
                {
                    b.HasOne("MultiPlanerAPI.Models.User", "User")
                        .WithOne("UserSettings")
                        .HasForeignKey("MultiPlanerAPI.Models.UserSettings", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_settings_user");

                    b.OwnsOne("MultiPlanerSharedModels.JSON.UserSettingsContent", "Settings", b1 =>
                        {
                            b1.Property<int>("UserSettingsIdUser");

                            b1.Property<bool>("EmailNotifications");

                            b1.Property<string>("Language")
                                .IsRequired();

                            b1.Property<string>("Theme")
                                .IsRequired();

                            b1.HasKey("UserSettingsIdUser");

                            b1.ToTable("user_settings", "dbo");

                            b1
                                .ToJson("Settings")
                                .HasColumnType("nvarchar(max)");

                            b1.WithOwner()
                                .HasForeignKey("UserSettingsIdUser");
                        });

                    b.Navigation("Settings")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.Calendar", b =>
                {
                    b.Navigation("CalendarCalendarLists");

                    b.Navigation("CalendarEvents");

                    b.Navigation("CalendarPolls");

                    b.Navigation("CalendarStates");

                    b.Navigation("CalendarUsers");

                    b.Navigation("MessageRoom");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.CalendarList", b =>
                {
                    b.Navigation("CalendarCalendarLists");

                    b.Navigation("SubLists");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.Event", b =>
                {
                    b.Navigation("CalendarEvent");

                    b.Navigation("EventData");

                    b.Navigation("EventUsers");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.Menu", b =>
                {
                    b.Navigation("CalendarLists");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.MessageRoom", b =>
                {
                    b.Navigation("MessageRoomMessages");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.Poll", b =>
                {
                    b.Navigation("CalendarPolls");

                    b.Navigation("PollUsers");
                });

            modelBuilder.Entity("MultiPlanerAPI.Models.User", b =>
                {
                    b.Navigation("CalendarLists");

                    b.Navigation("CalendarStates");

                    b.Navigation("CalendarUsers");

                    b.Navigation("CreatedEvents");

                    b.Navigation("EventUsers");

                    b.Navigation("Menu");

                    b.Navigation("PollUsers");

                    b.Navigation("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
